#pragma once

#include "exceptions/MyException.h"
#include "exceptions/RangeException.h"
#include "exceptions/ConfigException.h"
#include "exceptions/OperationException.h"
#include "exceptions/DBOperationCancelledException.h"
#include "exceptions/NoAuthException.h"
#include "exceptions/GuestUpdateException.h"
#include "exceptions/NonUniqueException.h"
#include "exceptions/AlreadyGettedOutException.h"
#include "exceptions/NotBookCopyIDException.h"
#include "exceptions/AlreadyArchievedException.h"
#include "exceptions/NotGettedOutException.h"
#include "exceptions/UserGetOutSomethingException.h"
#include "exceptions/BookGettedOutBySomebodyException.h"
#include "exceptions/NotISBNException.h"
